### ISSUE TITLE
OR NOT AVALABLE AND NOT GETTING SESSION AFTER SCANNING

### ISSUE THREAD

**Issue by tixxis** [DarkMakerofc/Queen-Elisa-MD-V2#35]
Sometimes the QR isn't available. If when it is available If we scan the qr session is not coming.after scanning qr session I'd is not getting to the number

**Comment by ajsubal555** [comment]
Same problem

**Comment by DarkMakerofc** [comment]
> Sometimes the QR isn't available. If when it is available If we scan the qr session is not coming.after scanning qr session I'd is not getting to the number

ok wait for next update

**Comment by ajsubal555** [comment]
I run the code and it is showing 20 issue please help
